feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView, AboutPageView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
    path('about/', AboutPageView.as_view(), name='about'),
    
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),


]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    #Title not in video!!!! Add everwhere!!!
    title = models.CharField(max_length=30, blank=False, null=False, default='')
    text = models.TextField(max_length=140, blank=False, null=False)
    image = models.ImageField(default='')
    date = models.DateTimeField(auto_now_add=True,
                                blank=True, null=True)

   

    def __str__(self):
        return self.title
        

feed/forms.py
from django import forms

class PostForm(forms.Form):
    title = forms.CharField()   
    image = forms.FileField()
    description = forms.CharField()
    

feed/views.py
from django.views.generic import TemplateView, DetailView, FormView
#ccbv.co.uk for help with Templateview and detailview etc..
from .models import Post
from .forms import PostForm
from django.contrib import messages




# Create your views here.

class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context

class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post

def dispatch(self, request, *args, **kwargs):
    self.request = request
    return super().dispatch(request, *args, **kwargs)


class AddPostView(FormView):
    template_name = 'new_post.html'
    form_class = PostForm
    success_url = '/'

    def form_valid(self, form):
        new_object = Post.objects.create(
            title = form.cleaned_data['title'],
            image=form.cleaned_data['image'],
            text=form.cleaned_data['description'],
            
        )
        messages.add_message(self.request, messages.SUCCESS, 'Post Submitted!' )
        return super().form_valid(form)
        

class AboutPageView(TemplateView):  # new
    template_name = 'about.html'

  

        


    

templates/about.html
{% extends 'base.htm' %}

{% block title %}REAPERSROOMS{% endblock title %}

{% block content %}
<h1 class='text-center my-4 text-danger'>About page</h1>

<br>
<br>
<br>
<hr class='danger'>
<p class='text-white'>
    This website was created for Reapers182 members to share and document in game experiences.
    
    Whether it's setting up inner clan matches such as 1v1s, MP Scrims or BR games, post it!
    
    Also tournament reminders, victories and just plain fun moments can all be shared with members outside the realms of Facebook, and inside our own little realm called ReapersRooms!
    

</p>
<hr>
{% endblock content %}

templates/base.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    
</head>
<body class='bg-dark'>
    
    {% include "includes/navbar.html" %}
    {% if messages %}
        {% for message in messages %}        
            <div class="bg-{% if message.tags %}{{ message.tags }}{% else %}success{% endif %} bg-danger text-center text-white py-4">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    
    
    
    

    <div class="container">
    {% block content %}
    {% endblock %}
    
    
    </div>
</body>
</html>

templates/detail.html
{% extends 'base.htm' %}

{% block title %}Detail view{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-sm-7 offset-sm-2 pt-5 text-white text-center">
            <h3>{{ object.title }}</h3>
            <p>{{ object.text }}</p>
            <img src="{{object.image.url}}" class="img-fluid rounded border border-danger">  
            <hr>  
        </div>
    </div>
    
{% endblock content %}

templates/home.html
{% extends 'base.htm' %}
{% load thumbnail %}


{% block title %}REAPERSROOMS{% endblock title %}

{% block content %}
<h2 class='text-center text-white my-4 py-4'>Posts Feed</h2>
<hr>
    <div class="row">   
    {% for post in posts %}                   
        <!--!!!!github/jazzband/sorl-thumbnail-->    
    <div class="col-sm-6 col-md-3">     
    <div class="card my-4 border-bottom border-danger">
        {% thumbnail post.image "200x200" crop="center" as im %}
            <img src="{{ im.url }}" class="card-img-top" alt="...">
        {% endthumbnail %}
    
    <div class="card-body bg-dark bg-gradient text-white">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.text }}</p>
        <p class='card-date'>{{ post.date }}</p>
        <a href="{% url 'feed:detail' post.id %}" class="btn btn-danger bg-gradient text-dark">View Post</a>
    </div>
    </div>
    </div>
    
    
    {% empty %}
        <h3 class='col-sm-6 offset-3 text-center my-4 text-danger'>WELCOME TO REAPERSROOMS</h3>
        <p class='col-sm-6 offset-3 text-center my-4 text-white'>Be the first to create a post</p>
        <button class='btn btn-danger col-sm-6 offset-3 my-4 bg-gradient text-white'>
        <a href="{% url 'feed:post' %}">FIRST POST</a>
        </button>

    {% endfor %}
    </div>
{% endblock content %}

templates/includes/navbar.html
<nav class="navbar border rounded mx-5 border-danger navbar-expand navbar-dark bg-danger bg-gradient sticky-xl-top mt-3 " aria-label="Second navbar example">
        <div class="container-fluid  ">
            <a class="navbar-brand text-dark" href="/">REAPERSROOMS</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02"
                aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarsExample02 text-danger">
                <ul class="navbar-nav me-auto ">
                    <li class="nav-item">
                        <a class="nav-link text-white" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'feed:post' %}">New Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'feed:about' %}">About</a>
                    </li>
                </ul>
                
            </div>
        </div>
    </nav>

templates/new_post.html
{% extends 'base.htm' %}

{% block title %}Upload Image{% endblock title %}Upload Image

{% block content %}

<div class='card my-5 bg-dark text-white rounded border-danger'>
    <form method="POST" action="" enctype="multipart/form-data" class="col-sm-4 offset-4">
        <h3 class="my-5">Create a Post</h3>
        <br>
        {% csrf_token %}
        {{ form.as_p }}
        
        <div>
            <button type='submit' class='btn btn-danger my-4'>Submit</button>
        </div>
    </form>
</div>

{% endblock content %}